=begin
#MUDBASESDK

#MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

The version of the OpenAPI document: 1.3.15
Contact: support@mudbase.dev
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Mudbase::BackupsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BackupsApi' do
  before do
    # run before each test
    @api_instance = Mudbase::BackupsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BackupsApi' do
    it 'should create an instance of BackupsApi' do
      expect(@api_instance).to be_instance_of(Mudbase::BackupsApi)
    end
  end

  # unit tests for create_backup
  # Create project backup
  # Create a backup of project data, optionally including files and wallets. Supports both JWT Bearer token and API key authentication.
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @option opts [CreateBackupRequest] :create_backup_request 
  # @return [CreateBackup201Response]
  describe 'create_backup test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_backup
  # Delete backup
  # Delete a project backup. Supports both JWT Bearer token and API key authentication.
  # @param project_id 
  # @param backup_id 
  # @param [Hash] opts the optional parameters
  # @return [DeleteBackup200Response]
  describe 'delete_backup test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_backups
  # List project backups
  # Get all backups for a project. Supports both JWT Bearer token and API key authentication.
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @return [ListBackups200Response]
  describe 'list_backups test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for restore_backup
  # Restore from backup
  # Restore project data from a backup. Supports replace or merge modes. Supports both JWT Bearer token and API key authentication.
  # @param project_id 
  # @param backup_id 
  # @param restore_backup_request 
  # @param [Hash] opts the optional parameters
  # @return [RestoreBackup200Response]
  describe 'restore_backup test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
