=begin
#MUDBASESDK

#MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

The version of the OpenAPI document: 1.3.16
Contact: support@mudbase.dev
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Mudbase::RolesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RolesApi' do
  before do
    # run before each test
    @api_instance = Mudbase::RolesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RolesApi' do
    it 'should create an instance of RolesApi' do
      expect(@api_instance).to be_instance_of(Mudbase::RolesApi)
    end
  end

  # unit tests for assign_role
  # ~~Assign custom role to user~~ (deprecated)
  # Assign a custom role to a user in the organization. Requires JWT Bearer token authentication. Both OrgBearerAuth and ProjectBearerAuth are supported (they use the same JWT token format). These are organization-level operations. 
  # @param org_id 
  # @param user_id 
  # @param assign_role_request 
  # @param [Hash] opts the optional parameters
  # @return [AssignRole200Response]
  describe 'assign_role test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for check_permissions
  # ~~Check user permissions~~ (deprecated)
  # Get all permissions for a user (system + custom role combined)
  # @param org_id 
  # @param user_id 
  # @param [Hash] opts the optional parameters
  # @return [CheckPermissions200Response]
  describe 'check_permissions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_role
  # ~~Create custom role~~ (deprecated)
  # Create a new custom role with specific permissions for your organization. Requires JWT Bearer token authentication. Both OrgBearerAuth and ProjectBearerAuth are supported (they use the same JWT token format). These are organization-level operations. 
  # @param org_id 
  # @param create_role_request 
  # @param [Hash] opts the optional parameters
  # @return [CreateRole201Response]
  describe 'create_role test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_role
  # ~~Delete role~~ (deprecated)
  # Delete a custom role. Cannot delete system roles or roles with active users. Requires JWT Bearer token authentication. Both OrgBearerAuth and ProjectBearerAuth are supported (they use the same JWT token format). These are organization-level operations. 
  # @param org_id 
  # @param role_id 
  # @param [Hash] opts the optional parameters
  # @return [DeleteRole200Response]
  describe 'delete_role test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_role
  # ~~Get role details~~ (deprecated)
  # Get details of a specific custom role. Requires: OrgBearerAuth (organization-level authentication only). 
  # @param org_id 
  # @param role_id 
  # @param [Hash] opts the optional parameters
  # @return [GetRole200Response]
  describe 'get_role test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_users_by_role
  # ~~Get users with specific role~~ (deprecated)
  # @param org_id 
  # @param role_slug 
  # @param [Hash] opts the optional parameters
  # @return [GetUsersByRole200Response]
  describe 'get_users_by_role test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_roles
  # ~~List all roles~~ (deprecated)
  # Get all custom roles for the organization. Requires: OrgBearerAuth (organization-level authentication only). 
  # @param org_id 
  # @param [Hash] opts the optional parameters
  # @return [ListRoles200Response]
  describe 'list_roles test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for remove_role
  # ~~Remove custom role from user~~ (deprecated)
  # Remove a custom role from a user in the organization. Requires JWT Bearer token authentication. Both OrgBearerAuth and ProjectBearerAuth are supported (they use the same JWT token format). These are organization-level operations. 
  # @param org_id 
  # @param user_id 
  # @param [Hash] opts the optional parameters
  # @return [AssignRole200Response]
  describe 'remove_role test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_role
  # ~~Update role~~ (deprecated)
  # @param org_id 
  # @param role_id 
  # @param update_role_request 
  # @param [Hash] opts the optional parameters
  # @return [UpdateRole200Response]
  describe 'update_role test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
