=begin
#MUDBASESDK

#MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

The version of the OpenAPI document: 1.3.12
Contact: support@mudbase.dev
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'date'
require 'time'

module Mudbase
  # Partial org limit overrides for platform admins. At least one property required. Keys match `PLANS[*].limits` in the backend; integers are non-negative or null for unlimited. 
  class AdminOrgLimitsPatchRequest < ApiModelBase
    attr_accessor :projects

    attr_accessor :storage

    attr_accessor :bandwidth

    attr_accessor :api_calls

    attr_accessor :buckets

    attr_accessor :collections

    attr_accessor :realtime_connections

    attr_accessor :realtime_messages

    attr_accessor :chat_messages_per_month

    attr_accessor :api_keys_per_project

    attr_accessor :webhooks_per_project

    attr_accessor :functions_per_project

    attr_accessor :function_invocations_per_month

    attr_accessor :messaging_messages_per_month

    attr_accessor :sms_per_month

    attr_accessor :chat_channels_per_project

    attr_accessor :backups_per_project

    attr_accessor :restores_per_month

    attr_accessor :integrations_per_project

    attr_accessor :roles_per_org

    attr_accessor :alerts_per_project

    attr_accessor :blockchain_chains

    attr_accessor :team_users

    attr_accessor :bug_analysis

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'projects' => :'projects',
        :'storage' => :'storage',
        :'bandwidth' => :'bandwidth',
        :'api_calls' => :'apiCalls',
        :'buckets' => :'buckets',
        :'collections' => :'collections',
        :'realtime_connections' => :'realtimeConnections',
        :'realtime_messages' => :'realtimeMessages',
        :'chat_messages_per_month' => :'chatMessagesPerMonth',
        :'api_keys_per_project' => :'apiKeysPerProject',
        :'webhooks_per_project' => :'webhooksPerProject',
        :'functions_per_project' => :'functionsPerProject',
        :'function_invocations_per_month' => :'functionInvocationsPerMonth',
        :'messaging_messages_per_month' => :'messagingMessagesPerMonth',
        :'sms_per_month' => :'smsPerMonth',
        :'chat_channels_per_project' => :'chatChannelsPerProject',
        :'backups_per_project' => :'backupsPerProject',
        :'restores_per_month' => :'restoresPerMonth',
        :'integrations_per_project' => :'integrationsPerProject',
        :'roles_per_org' => :'rolesPerOrg',
        :'alerts_per_project' => :'alertsPerProject',
        :'blockchain_chains' => :'blockchainChains',
        :'team_users' => :'teamUsers',
        :'bug_analysis' => :'bugAnalysis'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'projects' => :'Integer',
        :'storage' => :'Integer',
        :'bandwidth' => :'Integer',
        :'api_calls' => :'Integer',
        :'buckets' => :'Integer',
        :'collections' => :'Integer',
        :'realtime_connections' => :'Integer',
        :'realtime_messages' => :'Integer',
        :'chat_messages_per_month' => :'Integer',
        :'api_keys_per_project' => :'Integer',
        :'webhooks_per_project' => :'Integer',
        :'functions_per_project' => :'Integer',
        :'function_invocations_per_month' => :'Integer',
        :'messaging_messages_per_month' => :'Integer',
        :'sms_per_month' => :'Integer',
        :'chat_channels_per_project' => :'Integer',
        :'backups_per_project' => :'Integer',
        :'restores_per_month' => :'Integer',
        :'integrations_per_project' => :'Integer',
        :'roles_per_org' => :'Integer',
        :'alerts_per_project' => :'Integer',
        :'blockchain_chains' => :'Integer',
        :'team_users' => :'Integer',
        :'bug_analysis' => :'AdminOrgLimitsPatchRequestBugAnalysis'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'projects',
        :'storage',
        :'bandwidth',
        :'api_calls',
        :'buckets',
        :'collections',
        :'realtime_connections',
        :'realtime_messages',
        :'chat_messages_per_month',
        :'api_keys_per_project',
        :'webhooks_per_project',
        :'functions_per_project',
        :'function_invocations_per_month',
        :'messaging_messages_per_month',
        :'sms_per_month',
        :'chat_channels_per_project',
        :'backups_per_project',
        :'restores_per_month',
        :'integrations_per_project',
        :'roles_per_org',
        :'alerts_per_project',
        :'blockchain_chains',
        :'team_users',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Mudbase::AdminOrgLimitsPatchRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Mudbase::AdminOrgLimitsPatchRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'projects')
        self.projects = attributes[:'projects']
      end

      if attributes.key?(:'storage')
        self.storage = attributes[:'storage']
      end

      if attributes.key?(:'bandwidth')
        self.bandwidth = attributes[:'bandwidth']
      end

      if attributes.key?(:'api_calls')
        self.api_calls = attributes[:'api_calls']
      end

      if attributes.key?(:'buckets')
        self.buckets = attributes[:'buckets']
      end

      if attributes.key?(:'collections')
        self.collections = attributes[:'collections']
      end

      if attributes.key?(:'realtime_connections')
        self.realtime_connections = attributes[:'realtime_connections']
      end

      if attributes.key?(:'realtime_messages')
        self.realtime_messages = attributes[:'realtime_messages']
      end

      if attributes.key?(:'chat_messages_per_month')
        self.chat_messages_per_month = attributes[:'chat_messages_per_month']
      end

      if attributes.key?(:'api_keys_per_project')
        self.api_keys_per_project = attributes[:'api_keys_per_project']
      end

      if attributes.key?(:'webhooks_per_project')
        self.webhooks_per_project = attributes[:'webhooks_per_project']
      end

      if attributes.key?(:'functions_per_project')
        self.functions_per_project = attributes[:'functions_per_project']
      end

      if attributes.key?(:'function_invocations_per_month')
        self.function_invocations_per_month = attributes[:'function_invocations_per_month']
      end

      if attributes.key?(:'messaging_messages_per_month')
        self.messaging_messages_per_month = attributes[:'messaging_messages_per_month']
      end

      if attributes.key?(:'sms_per_month')
        self.sms_per_month = attributes[:'sms_per_month']
      end

      if attributes.key?(:'chat_channels_per_project')
        self.chat_channels_per_project = attributes[:'chat_channels_per_project']
      end

      if attributes.key?(:'backups_per_project')
        self.backups_per_project = attributes[:'backups_per_project']
      end

      if attributes.key?(:'restores_per_month')
        self.restores_per_month = attributes[:'restores_per_month']
      end

      if attributes.key?(:'integrations_per_project')
        self.integrations_per_project = attributes[:'integrations_per_project']
      end

      if attributes.key?(:'roles_per_org')
        self.roles_per_org = attributes[:'roles_per_org']
      end

      if attributes.key?(:'alerts_per_project')
        self.alerts_per_project = attributes[:'alerts_per_project']
      end

      if attributes.key?(:'blockchain_chains')
        self.blockchain_chains = attributes[:'blockchain_chains']
      end

      if attributes.key?(:'team_users')
        self.team_users = attributes[:'team_users']
      end

      if attributes.key?(:'bug_analysis')
        self.bug_analysis = attributes[:'bug_analysis']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@projects.nil? && @projects < 0
        invalid_properties.push('invalid value for "projects", must be greater than or equal to 0.')
      end

      if !@storage.nil? && @storage < 0
        invalid_properties.push('invalid value for "storage", must be greater than or equal to 0.')
      end

      if !@bandwidth.nil? && @bandwidth < 0
        invalid_properties.push('invalid value for "bandwidth", must be greater than or equal to 0.')
      end

      if !@api_calls.nil? && @api_calls < 0
        invalid_properties.push('invalid value for "api_calls", must be greater than or equal to 0.')
      end

      if !@buckets.nil? && @buckets < 0
        invalid_properties.push('invalid value for "buckets", must be greater than or equal to 0.')
      end

      if !@collections.nil? && @collections < 0
        invalid_properties.push('invalid value for "collections", must be greater than or equal to 0.')
      end

      if !@realtime_connections.nil? && @realtime_connections < 0
        invalid_properties.push('invalid value for "realtime_connections", must be greater than or equal to 0.')
      end

      if !@realtime_messages.nil? && @realtime_messages < 0
        invalid_properties.push('invalid value for "realtime_messages", must be greater than or equal to 0.')
      end

      if !@chat_messages_per_month.nil? && @chat_messages_per_month < 0
        invalid_properties.push('invalid value for "chat_messages_per_month", must be greater than or equal to 0.')
      end

      if !@api_keys_per_project.nil? && @api_keys_per_project < 0
        invalid_properties.push('invalid value for "api_keys_per_project", must be greater than or equal to 0.')
      end

      if !@webhooks_per_project.nil? && @webhooks_per_project < 0
        invalid_properties.push('invalid value for "webhooks_per_project", must be greater than or equal to 0.')
      end

      if !@functions_per_project.nil? && @functions_per_project < 0
        invalid_properties.push('invalid value for "functions_per_project", must be greater than or equal to 0.')
      end

      if !@function_invocations_per_month.nil? && @function_invocations_per_month < 0
        invalid_properties.push('invalid value for "function_invocations_per_month", must be greater than or equal to 0.')
      end

      if !@messaging_messages_per_month.nil? && @messaging_messages_per_month < 0
        invalid_properties.push('invalid value for "messaging_messages_per_month", must be greater than or equal to 0.')
      end

      if !@sms_per_month.nil? && @sms_per_month < 0
        invalid_properties.push('invalid value for "sms_per_month", must be greater than or equal to 0.')
      end

      if !@chat_channels_per_project.nil? && @chat_channels_per_project < 0
        invalid_properties.push('invalid value for "chat_channels_per_project", must be greater than or equal to 0.')
      end

      if !@backups_per_project.nil? && @backups_per_project < 0
        invalid_properties.push('invalid value for "backups_per_project", must be greater than or equal to 0.')
      end

      if !@restores_per_month.nil? && @restores_per_month < 0
        invalid_properties.push('invalid value for "restores_per_month", must be greater than or equal to 0.')
      end

      if !@integrations_per_project.nil? && @integrations_per_project < 0
        invalid_properties.push('invalid value for "integrations_per_project", must be greater than or equal to 0.')
      end

      if !@roles_per_org.nil? && @roles_per_org < 0
        invalid_properties.push('invalid value for "roles_per_org", must be greater than or equal to 0.')
      end

      if !@alerts_per_project.nil? && @alerts_per_project < 0
        invalid_properties.push('invalid value for "alerts_per_project", must be greater than or equal to 0.')
      end

      if !@blockchain_chains.nil? && @blockchain_chains < 0
        invalid_properties.push('invalid value for "blockchain_chains", must be greater than or equal to 0.')
      end

      if !@team_users.nil? && @team_users < 0
        invalid_properties.push('invalid value for "team_users", must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@projects.nil? && @projects < 0
      return false if !@storage.nil? && @storage < 0
      return false if !@bandwidth.nil? && @bandwidth < 0
      return false if !@api_calls.nil? && @api_calls < 0
      return false if !@buckets.nil? && @buckets < 0
      return false if !@collections.nil? && @collections < 0
      return false if !@realtime_connections.nil? && @realtime_connections < 0
      return false if !@realtime_messages.nil? && @realtime_messages < 0
      return false if !@chat_messages_per_month.nil? && @chat_messages_per_month < 0
      return false if !@api_keys_per_project.nil? && @api_keys_per_project < 0
      return false if !@webhooks_per_project.nil? && @webhooks_per_project < 0
      return false if !@functions_per_project.nil? && @functions_per_project < 0
      return false if !@function_invocations_per_month.nil? && @function_invocations_per_month < 0
      return false if !@messaging_messages_per_month.nil? && @messaging_messages_per_month < 0
      return false if !@sms_per_month.nil? && @sms_per_month < 0
      return false if !@chat_channels_per_project.nil? && @chat_channels_per_project < 0
      return false if !@backups_per_project.nil? && @backups_per_project < 0
      return false if !@restores_per_month.nil? && @restores_per_month < 0
      return false if !@integrations_per_project.nil? && @integrations_per_project < 0
      return false if !@roles_per_org.nil? && @roles_per_org < 0
      return false if !@alerts_per_project.nil? && @alerts_per_project < 0
      return false if !@blockchain_chains.nil? && @blockchain_chains < 0
      return false if !@team_users.nil? && @team_users < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] projects Value to be assigned
    def projects=(projects)
      if !projects.nil? && projects < 0
        fail ArgumentError, 'invalid value for "projects", must be greater than or equal to 0.'
      end

      @projects = projects
    end

    # Custom attribute writer method with validation
    # @param [Object] storage Value to be assigned
    def storage=(storage)
      if !storage.nil? && storage < 0
        fail ArgumentError, 'invalid value for "storage", must be greater than or equal to 0.'
      end

      @storage = storage
    end

    # Custom attribute writer method with validation
    # @param [Object] bandwidth Value to be assigned
    def bandwidth=(bandwidth)
      if !bandwidth.nil? && bandwidth < 0
        fail ArgumentError, 'invalid value for "bandwidth", must be greater than or equal to 0.'
      end

      @bandwidth = bandwidth
    end

    # Custom attribute writer method with validation
    # @param [Object] api_calls Value to be assigned
    def api_calls=(api_calls)
      if !api_calls.nil? && api_calls < 0
        fail ArgumentError, 'invalid value for "api_calls", must be greater than or equal to 0.'
      end

      @api_calls = api_calls
    end

    # Custom attribute writer method with validation
    # @param [Object] buckets Value to be assigned
    def buckets=(buckets)
      if !buckets.nil? && buckets < 0
        fail ArgumentError, 'invalid value for "buckets", must be greater than or equal to 0.'
      end

      @buckets = buckets
    end

    # Custom attribute writer method with validation
    # @param [Object] collections Value to be assigned
    def collections=(collections)
      if !collections.nil? && collections < 0
        fail ArgumentError, 'invalid value for "collections", must be greater than or equal to 0.'
      end

      @collections = collections
    end

    # Custom attribute writer method with validation
    # @param [Object] realtime_connections Value to be assigned
    def realtime_connections=(realtime_connections)
      if !realtime_connections.nil? && realtime_connections < 0
        fail ArgumentError, 'invalid value for "realtime_connections", must be greater than or equal to 0.'
      end

      @realtime_connections = realtime_connections
    end

    # Custom attribute writer method with validation
    # @param [Object] realtime_messages Value to be assigned
    def realtime_messages=(realtime_messages)
      if !realtime_messages.nil? && realtime_messages < 0
        fail ArgumentError, 'invalid value for "realtime_messages", must be greater than or equal to 0.'
      end

      @realtime_messages = realtime_messages
    end

    # Custom attribute writer method with validation
    # @param [Object] chat_messages_per_month Value to be assigned
    def chat_messages_per_month=(chat_messages_per_month)
      if !chat_messages_per_month.nil? && chat_messages_per_month < 0
        fail ArgumentError, 'invalid value for "chat_messages_per_month", must be greater than or equal to 0.'
      end

      @chat_messages_per_month = chat_messages_per_month
    end

    # Custom attribute writer method with validation
    # @param [Object] api_keys_per_project Value to be assigned
    def api_keys_per_project=(api_keys_per_project)
      if !api_keys_per_project.nil? && api_keys_per_project < 0
        fail ArgumentError, 'invalid value for "api_keys_per_project", must be greater than or equal to 0.'
      end

      @api_keys_per_project = api_keys_per_project
    end

    # Custom attribute writer method with validation
    # @param [Object] webhooks_per_project Value to be assigned
    def webhooks_per_project=(webhooks_per_project)
      if !webhooks_per_project.nil? && webhooks_per_project < 0
        fail ArgumentError, 'invalid value for "webhooks_per_project", must be greater than or equal to 0.'
      end

      @webhooks_per_project = webhooks_per_project
    end

    # Custom attribute writer method with validation
    # @param [Object] functions_per_project Value to be assigned
    def functions_per_project=(functions_per_project)
      if !functions_per_project.nil? && functions_per_project < 0
        fail ArgumentError, 'invalid value for "functions_per_project", must be greater than or equal to 0.'
      end

      @functions_per_project = functions_per_project
    end

    # Custom attribute writer method with validation
    # @param [Object] function_invocations_per_month Value to be assigned
    def function_invocations_per_month=(function_invocations_per_month)
      if !function_invocations_per_month.nil? && function_invocations_per_month < 0
        fail ArgumentError, 'invalid value for "function_invocations_per_month", must be greater than or equal to 0.'
      end

      @function_invocations_per_month = function_invocations_per_month
    end

    # Custom attribute writer method with validation
    # @param [Object] messaging_messages_per_month Value to be assigned
    def messaging_messages_per_month=(messaging_messages_per_month)
      if !messaging_messages_per_month.nil? && messaging_messages_per_month < 0
        fail ArgumentError, 'invalid value for "messaging_messages_per_month", must be greater than or equal to 0.'
      end

      @messaging_messages_per_month = messaging_messages_per_month
    end

    # Custom attribute writer method with validation
    # @param [Object] sms_per_month Value to be assigned
    def sms_per_month=(sms_per_month)
      if !sms_per_month.nil? && sms_per_month < 0
        fail ArgumentError, 'invalid value for "sms_per_month", must be greater than or equal to 0.'
      end

      @sms_per_month = sms_per_month
    end

    # Custom attribute writer method with validation
    # @param [Object] chat_channels_per_project Value to be assigned
    def chat_channels_per_project=(chat_channels_per_project)
      if !chat_channels_per_project.nil? && chat_channels_per_project < 0
        fail ArgumentError, 'invalid value for "chat_channels_per_project", must be greater than or equal to 0.'
      end

      @chat_channels_per_project = chat_channels_per_project
    end

    # Custom attribute writer method with validation
    # @param [Object] backups_per_project Value to be assigned
    def backups_per_project=(backups_per_project)
      if !backups_per_project.nil? && backups_per_project < 0
        fail ArgumentError, 'invalid value for "backups_per_project", must be greater than or equal to 0.'
      end

      @backups_per_project = backups_per_project
    end

    # Custom attribute writer method with validation
    # @param [Object] restores_per_month Value to be assigned
    def restores_per_month=(restores_per_month)
      if !restores_per_month.nil? && restores_per_month < 0
        fail ArgumentError, 'invalid value for "restores_per_month", must be greater than or equal to 0.'
      end

      @restores_per_month = restores_per_month
    end

    # Custom attribute writer method with validation
    # @param [Object] integrations_per_project Value to be assigned
    def integrations_per_project=(integrations_per_project)
      if !integrations_per_project.nil? && integrations_per_project < 0
        fail ArgumentError, 'invalid value for "integrations_per_project", must be greater than or equal to 0.'
      end

      @integrations_per_project = integrations_per_project
    end

    # Custom attribute writer method with validation
    # @param [Object] roles_per_org Value to be assigned
    def roles_per_org=(roles_per_org)
      if !roles_per_org.nil? && roles_per_org < 0
        fail ArgumentError, 'invalid value for "roles_per_org", must be greater than or equal to 0.'
      end

      @roles_per_org = roles_per_org
    end

    # Custom attribute writer method with validation
    # @param [Object] alerts_per_project Value to be assigned
    def alerts_per_project=(alerts_per_project)
      if !alerts_per_project.nil? && alerts_per_project < 0
        fail ArgumentError, 'invalid value for "alerts_per_project", must be greater than or equal to 0.'
      end

      @alerts_per_project = alerts_per_project
    end

    # Custom attribute writer method with validation
    # @param [Object] blockchain_chains Value to be assigned
    def blockchain_chains=(blockchain_chains)
      if !blockchain_chains.nil? && blockchain_chains < 0
        fail ArgumentError, 'invalid value for "blockchain_chains", must be greater than or equal to 0.'
      end

      @blockchain_chains = blockchain_chains
    end

    # Custom attribute writer method with validation
    # @param [Object] team_users Value to be assigned
    def team_users=(team_users)
      if !team_users.nil? && team_users < 0
        fail ArgumentError, 'invalid value for "team_users", must be greater than or equal to 0.'
      end

      @team_users = team_users
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          projects == o.projects &&
          storage == o.storage &&
          bandwidth == o.bandwidth &&
          api_calls == o.api_calls &&
          buckets == o.buckets &&
          collections == o.collections &&
          realtime_connections == o.realtime_connections &&
          realtime_messages == o.realtime_messages &&
          chat_messages_per_month == o.chat_messages_per_month &&
          api_keys_per_project == o.api_keys_per_project &&
          webhooks_per_project == o.webhooks_per_project &&
          functions_per_project == o.functions_per_project &&
          function_invocations_per_month == o.function_invocations_per_month &&
          messaging_messages_per_month == o.messaging_messages_per_month &&
          sms_per_month == o.sms_per_month &&
          chat_channels_per_project == o.chat_channels_per_project &&
          backups_per_project == o.backups_per_project &&
          restores_per_month == o.restores_per_month &&
          integrations_per_project == o.integrations_per_project &&
          roles_per_org == o.roles_per_org &&
          alerts_per_project == o.alerts_per_project &&
          blockchain_chains == o.blockchain_chains &&
          team_users == o.team_users &&
          bug_analysis == o.bug_analysis
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [projects, storage, bandwidth, api_calls, buckets, collections, realtime_connections, realtime_messages, chat_messages_per_month, api_keys_per_project, webhooks_per_project, functions_per_project, function_invocations_per_month, messaging_messages_per_month, sms_per_month, chat_channels_per_project, backups_per_project, restores_per_month, integrations_per_project, roles_per_org, alerts_per_project, blockchain_chains, team_users, bug_analysis].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
