=begin
#MUDBASESDK

#MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

The version of the OpenAPI document: 1.3.14
Contact: support@mudbase.dev
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'date'
require 'time'

module Mudbase
  class FunctionExecution < ApiModelBase
    attr_accessor :_id

    attr_accessor :executed_at

    attr_accessor :execution_time

    attr_accessor :success

    attr_accessor :payload

    attr_accessor :result

    attr_accessor :error

    attr_accessor :trigger_type

    attr_accessor :trigger_event

    attr_accessor :invoked_by

    attr_accessor :retry_count

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'_id' => :'_id',
        :'executed_at' => :'executedAt',
        :'execution_time' => :'executionTime',
        :'success' => :'success',
        :'payload' => :'payload',
        :'result' => :'result',
        :'error' => :'error',
        :'trigger_type' => :'triggerType',
        :'trigger_event' => :'triggerEvent',
        :'invoked_by' => :'invokedBy',
        :'retry_count' => :'retryCount'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'_id' => :'String',
        :'executed_at' => :'Time',
        :'execution_time' => :'Integer',
        :'success' => :'Boolean',
        :'payload' => :'Object',
        :'result' => :'Object',
        :'error' => :'String',
        :'trigger_type' => :'String',
        :'trigger_event' => :'String',
        :'invoked_by' => :'String',
        :'retry_count' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Mudbase::FunctionExecution` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Mudbase::FunctionExecution`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'_id')
        self._id = attributes[:'_id']
      end

      if attributes.key?(:'executed_at')
        self.executed_at = attributes[:'executed_at']
      end

      if attributes.key?(:'execution_time')
        self.execution_time = attributes[:'execution_time']
      end

      if attributes.key?(:'success')
        self.success = attributes[:'success']
      end

      if attributes.key?(:'payload')
        self.payload = attributes[:'payload']
      end

      if attributes.key?(:'result')
        self.result = attributes[:'result']
      end

      if attributes.key?(:'error')
        self.error = attributes[:'error']
      end

      if attributes.key?(:'trigger_type')
        self.trigger_type = attributes[:'trigger_type']
      end

      if attributes.key?(:'trigger_event')
        self.trigger_event = attributes[:'trigger_event']
      end

      if attributes.key?(:'invoked_by')
        self.invoked_by = attributes[:'invoked_by']
      end

      if attributes.key?(:'retry_count')
        self.retry_count = attributes[:'retry_count']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      invoked_by_validator = EnumAttributeValidator.new('String', ["manual", "api_key", "trigger", "cron"])
      return false unless invoked_by_validator.valid?(@invoked_by)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] invoked_by Object to be assigned
    def invoked_by=(invoked_by)
      validator = EnumAttributeValidator.new('String', ["manual", "api_key", "trigger", "cron"])
      unless validator.valid?(invoked_by)
        fail ArgumentError, "invalid value for \"invoked_by\", must be one of #{validator.allowable_values}."
      end
      @invoked_by = invoked_by
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          _id == o._id &&
          executed_at == o.executed_at &&
          execution_time == o.execution_time &&
          success == o.success &&
          payload == o.payload &&
          result == o.result &&
          error == o.error &&
          trigger_type == o.trigger_type &&
          trigger_event == o.trigger_event &&
          invoked_by == o.invoked_by &&
          retry_count == o.retry_count
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [_id, executed_at, execution_time, success, payload, result, error, trigger_type, trigger_event, invoked_by, retry_count].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
