=begin
#MUDBASESDK

#MUDBASE is a scalable, real-time, and secure Backend-as-a-Service (BaaS) platform  designed for modern applications. Built with custom logic, it offers fine-grained  control, extensibility, and enterprise-grade security.  ## Features - 🔐 Multi-provider authentication (30+ OAuth providers) - 📊 Real-time database with collections - 📁 File storage and management - 🔑 API key management with permissions - 🔗 Webhook system with retry logic - ⚡ Serverless functions - 💬 Multi-channel messaging (Push, Email, SMS) - 📈 Usage analytics and monitoring - 🌐 Real-time WebSocket events - 🔍 Full-text search capabilities - 💳 Billing: fiat only for project subscriptions and org BaaS checkout (platform fee split). On-chain billing is not exposed on these APIs (optional `crypto-payment-module/` in repo, not mounted by default). - 🏢 Enterprise / Phase 4: custom domains on Growth, Scale, and Enterprise (TXT DNS at `_mudbase-verify.<hostname>`); `settings.customDomainAddon` is optional (billing/legacy); dedicated DB migration script, periodic DNS recheck job, optional `infrastructureEnvironments[]` and edge/metering fields on `dedicated`. 

The version of the OpenAPI document: 1.3.13
Contact: support@mudbase.dev
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'date'
require 'time'

module Mudbase
  # Org API compact domain row: use **`dnsRecords`** for the Mudbase ownership TXT (purpose `mudbase_ownership`) and routing CNAME. Omits `hostnameNormalized`, `verificationToken`, `dnsTxtHost`, and `dnsTxtValue`. Omits `edge` when edge SSL is not configured. Optional keys with no value are omitted from JSON responses.
  class OrgDomainEntryOrgConsole < ApiModelBase
    attr_accessor :_id

    attr_accessor :hostname

    attr_accessor :status

    attr_accessor :is_primary

    attr_accessor :source

    attr_accessor :created_at

    attr_accessor :verified_at

    attr_accessor :last_verified_at

    attr_accessor :cname_submitted_at

    attr_accessor :cname_approved_at

    attr_accessor :custom_domain_verification_step

    attr_accessor :routing_cname_target

    attr_accessor :dns_records

    attr_accessor :platform_activation_pending

    attr_accessor :custom_domain_live_for_api_traffic

    attr_accessor :edge

    attr_accessor :fly_certificate_status

    attr_accessor :platform_dns_verification

    attr_accessor :platform_dns_verification_submitted_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'_id' => :'_id',
        :'hostname' => :'hostname',
        :'status' => :'status',
        :'is_primary' => :'isPrimary',
        :'source' => :'source',
        :'created_at' => :'createdAt',
        :'verified_at' => :'verifiedAt',
        :'last_verified_at' => :'lastVerifiedAt',
        :'cname_submitted_at' => :'cnameSubmittedAt',
        :'cname_approved_at' => :'cnameApprovedAt',
        :'custom_domain_verification_step' => :'customDomainVerificationStep',
        :'routing_cname_target' => :'routingCnameTarget',
        :'dns_records' => :'dnsRecords',
        :'platform_activation_pending' => :'platformActivationPending',
        :'custom_domain_live_for_api_traffic' => :'customDomainLiveForApiTraffic',
        :'edge' => :'edge',
        :'fly_certificate_status' => :'flyCertificateStatus',
        :'platform_dns_verification' => :'platformDnsVerification',
        :'platform_dns_verification_submitted_at' => :'platformDnsVerificationSubmittedAt'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'_id' => :'String',
        :'hostname' => :'String',
        :'status' => :'String',
        :'is_primary' => :'Boolean',
        :'source' => :'String',
        :'created_at' => :'Time',
        :'verified_at' => :'Time',
        :'last_verified_at' => :'Time',
        :'cname_submitted_at' => :'Time',
        :'cname_approved_at' => :'Time',
        :'custom_domain_verification_step' => :'Integer',
        :'routing_cname_target' => :'String',
        :'dns_records' => :'Array<OrgDnsRecord>',
        :'platform_activation_pending' => :'Boolean',
        :'custom_domain_live_for_api_traffic' => :'Boolean',
        :'edge' => :'OrgEdgeHints',
        :'fly_certificate_status' => :'String',
        :'platform_dns_verification' => :'OrgPlatformDnsVerificationCustomer',
        :'platform_dns_verification_submitted_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'verified_at',
        :'last_verified_at',
        :'cname_submitted_at',
        :'cname_approved_at',
        :'custom_domain_verification_step',
        :'routing_cname_target',
        :'fly_certificate_status',
        :'platform_dns_verification',
        :'platform_dns_verification_submitted_at'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Mudbase::OrgDomainEntryOrgConsole` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Mudbase::OrgDomainEntryOrgConsole`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'_id')
        self._id = attributes[:'_id']
      end

      if attributes.key?(:'hostname')
        self.hostname = attributes[:'hostname']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'is_primary')
        self.is_primary = attributes[:'is_primary']
      end

      if attributes.key?(:'source')
        self.source = attributes[:'source']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      end

      if attributes.key?(:'verified_at')
        self.verified_at = attributes[:'verified_at']
      end

      if attributes.key?(:'last_verified_at')
        self.last_verified_at = attributes[:'last_verified_at']
      end

      if attributes.key?(:'cname_submitted_at')
        self.cname_submitted_at = attributes[:'cname_submitted_at']
      end

      if attributes.key?(:'cname_approved_at')
        self.cname_approved_at = attributes[:'cname_approved_at']
      end

      if attributes.key?(:'custom_domain_verification_step')
        self.custom_domain_verification_step = attributes[:'custom_domain_verification_step']
      end

      if attributes.key?(:'routing_cname_target')
        self.routing_cname_target = attributes[:'routing_cname_target']
      end

      if attributes.key?(:'dns_records')
        if (value = attributes[:'dns_records']).is_a?(Array)
          self.dns_records = value
        end
      end

      if attributes.key?(:'platform_activation_pending')
        self.platform_activation_pending = attributes[:'platform_activation_pending']
      end

      if attributes.key?(:'custom_domain_live_for_api_traffic')
        self.custom_domain_live_for_api_traffic = attributes[:'custom_domain_live_for_api_traffic']
      end

      if attributes.key?(:'edge')
        self.edge = attributes[:'edge']
      end

      if attributes.key?(:'fly_certificate_status')
        self.fly_certificate_status = attributes[:'fly_certificate_status']
      end

      if attributes.key?(:'platform_dns_verification')
        self.platform_dns_verification = attributes[:'platform_dns_verification']
      end

      if attributes.key?(:'platform_dns_verification_submitted_at')
        self.platform_dns_verification_submitted_at = attributes[:'platform_dns_verification_submitted_at']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      source_validator = EnumAttributeValidator.new('String', ["manual", "api", "imported"])
      return false unless source_validator.valid?(@source)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] source Object to be assigned
    def source=(source)
      validator = EnumAttributeValidator.new('String', ["manual", "api", "imported"])
      unless validator.valid?(source)
        fail ArgumentError, "invalid value for \"source\", must be one of #{validator.allowable_values}."
      end
      @source = source
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          _id == o._id &&
          hostname == o.hostname &&
          status == o.status &&
          is_primary == o.is_primary &&
          source == o.source &&
          created_at == o.created_at &&
          verified_at == o.verified_at &&
          last_verified_at == o.last_verified_at &&
          cname_submitted_at == o.cname_submitted_at &&
          cname_approved_at == o.cname_approved_at &&
          custom_domain_verification_step == o.custom_domain_verification_step &&
          routing_cname_target == o.routing_cname_target &&
          dns_records == o.dns_records &&
          platform_activation_pending == o.platform_activation_pending &&
          custom_domain_live_for_api_traffic == o.custom_domain_live_for_api_traffic &&
          edge == o.edge &&
          fly_certificate_status == o.fly_certificate_status &&
          platform_dns_verification == o.platform_dns_verification &&
          platform_dns_verification_submitted_at == o.platform_dns_verification_submitted_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [_id, hostname, status, is_primary, source, created_at, verified_at, last_verified_at, cname_submitted_at, cname_approved_at, custom_domain_verification_step, routing_cname_target, dns_records, platform_activation_pending, custom_domain_live_for_api_traffic, edge, fly_certificate_status, platform_dns_verification, platform_dns_verification_submitted_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
